import {
  Activity,
  ArrowDownRight,
  ArrowRight,
  ArrowUpRight,
  Banknote,
  Bell,
  BookOpen,
  Bot,
  Briefcase,
  Building2,
  CalendarDays,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChevronDown,
  CircleCheck,
  CircleMinus,
  CircleX,
  ClipboardCheck,
  Clock,
  Coins,
  Diamond,
  Ear,
  ExternalLink,
  FileText,
  Flag,
  Flame,
  FlaskConical,
  Globe,
  GripVertical,
  Headset,
  Heart,
  Image,
  Inbox,
  LayoutDashboard,
  Lightbulb,
  ListOrdered,
  LogOut,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquareText,
  MessagesSquare,
  Octagon,
  PanelLeftClose,
  PanelLeftOpen,
  Percent,
  Pin,
  Play,
  Plug,
  Plus,
  RotateCcw,
  Scale,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  SlidersVertical,
  Sparkles,
  Split,
  SquareKanban,
  Star,
  Store,
  TrendingUp,
  TriangleAlert,
  Truck,
  Users,
  UsersRound,
  WandSparkles,
  Workflow,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

// §246: the portal's one icon set - professional SVG icons from lucide-react
// (already a dependency of the site, tree-shaken per icon, so nothing new is
// shipped). Callers use a meaningful name, never a glyph or an emoji.

const ICONS = {
  dashboard: LayoutDashboard,
  inbox: Inbox,
  conversations: MessagesSquare,
  customers: Users,
  quickReplies: MessageSquareText,
  approvals: CircleCheck,
  sales: ShoppingBag,
  salesDesk: Briefcase,
  pipeline: SquareKanban,
  cod: Banknote,
  courier: Truck,
  winback: RotateCcw,
  retention: Heart,
  marketing: Megaphone,
  sequences: ListOrdered,
  segments: ChartPie,
  growth: TrendingUp,
  automation: Zap,
  workflows: Workflow,
  rules: Scale,
  content: FileText,
  knowledgeBase: BookOpen,
  websiteAnalyzer: Globe,
  media: Image,
  insights: ChartLine,
  businessInsights: Lightbulb,
  analytics: ChartColumn,
  weekly: CalendarDays,
  activity: Activity,
  ai: Bot,
  configureAi: SlidersVertical,
  aiReport: ClipboardCheck,
  sandbox: FlaskConical,
  workspace: Building2,
  whatsapp: MessageCircle,
  setupWizard: WandSparkles,
  profile: Store,
  integrations: Plug,
  compliance: ShieldCheck,
  team: UsersRound,
  settings: Settings,
  sparkles: Sparkles,
  search: Search,
  chevronDown: ChevronDown,
  arrowRight: ArrowRight,
  sidebarClose: PanelLeftClose,
  sidebarOpen: PanelLeftOpen,
  externalLink: ExternalLink,
  expand: Maximize2,
  menu: Menu,
  close: X,
  plus: Plus,
  flame: Flame,
  alert: TriangleAlert,
  failed: CircleX,
  skipped: CircleMinus,
  revenue: Coins,
  star: Star,
  bell: Bell,
  logout: LogOut,
  clock: Clock,
  flag: Flag,
  stop: Octagon,
  split: Split,
  condition: Diamond,
  play: Play,
  grip: GripVertical,
  handoff: Headset,
  listen: Ear,
  percent: Percent,
  pin: Pin,
  trendUp: ArrowUpRight,
  trendDown: ArrowDownRight,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export default function PortalIcon({
  name,
  className = "h-4 w-4",
  strokeWidth = 1.8,
}: {
  name: IconName;
  className?: string;
  strokeWidth?: number;
}) {
  const Icon = ICONS[name];
  return <Icon aria-hidden="true" focusable="false" strokeWidth={strokeWidth} className={"shrink-0 " + className} />;
}
