"""Tests for batches 247-254: the hero OmniFlowBot.

A pre-rendered 3D robot (250; 251: arms as shoulder > elbow > wrist
chains, a looping 12s intro with head / face / body language, eyes that
lead the head; 252: open palms from a second render for a front wave and
gestures toward the viewer, timeline generated by motion.py, a taller
stage and bigger robot on phones; 253: smooth arms - the elbow leads the
lift, poses on the way are passed through, no sideways reach, a palm opens
only while its gesture runs; 254: natural hands - relaxed, palms to the
body, except the waving hand, whose open palm (cut from a wave render at
the hand's own size, fingers together) unfolds once the forearm is up;
WebP layers on one canvas in
public/bot, made by tools/bot-render) with live token-coloured overlays
(LED eyes, smile, chest meter), depth parallax + a per-layer cursor light,
standing on a light platform, with a CSS intro timeline (9.6s), the robot
in its own BotVisual file (249),
two channel arcs from the honest integrations list (Soon badge
for upcoming channels) and one small client
island (cursor tracking via CSS vars + rAF, offscreen pause, tap wave).
Static pins for the performance / token / accessibility laws, plus the
functional harness (hero_bot_harness.cjs: real TSX rendered with
react-dom/server).
"""
import glob
import os
import re
import shutil
import subprocess

import test_lib
from test_lib import check, summary

ROOT = "/tmp/p13/Omniflow/"
REPO = "/home/user/Omniflow/"
HERE = os.path.dirname(os.path.abspath(__file__))
BOT = "app/components/OmniFlowBot/"


def read(path):
    return open(ROOT + path, encoding="utf8").read()


print("== isolation ==")

FILES = sorted(os.path.basename(p) for p in glob.glob(ROOT + BOT + "*") if not p.endswith(".bak"))  # patcher backups are git-ignored
check("bot files", FILES == ["BotMotion.tsx", "BotVisual.tsx", "OmniFlowBot.module.css", "OmniFlowBot.tsx", "botChannels.ts"], FILES)
CONTAINER = read(BOT + "OmniFlowBot.tsx")
VISUAL_BOT = read(BOT + "BotVisual.tsx")
VIEW = CONTAINER + VISUAL_BOT
MOTION = read(BOT + "BotMotion.tsx")
CSS = read(BOT + "OmniFlowBot.module.css")
CHANNELS = read(BOT + "botChannels.ts")
ALL = VIEW + MOTION + CSS + CHANNELS
check("bot is a server component", '"use client"' not in VIEW and "useState" not in VIEW and "useEffect" not in VIEW, "no client code")
check("one client island", MOTION.startswith('"use client";') and '"use client"' not in CHANNELS, "BotMotion only")
check("props api", all(p in CONTAINER for p in ("intro = true,", "interactive = true,", "socialBubbles = true,", "cursorTracking = true,", "animated = true,",
                                             "label: string;", "copy: OmniFlowBotCopy;")), "props")
check("bot knows no cms", "getCopy" not in VIEW and "lib/marketing" not in VIEW and "lib/marketing" not in CHANNELS, "data via props")

HERO = read("app/components/Hero.tsx")
check("hero stays dumb", "<HeroVisual />" in HERO and "OmniFlowBot" not in HERO, "slot only")
VISUAL = read("app/components/hero/HeroVisual.tsx")
check("visual slot swap", "{heroVisualAsset ? (\n        <AIVisual asset={heroVisualAsset} fallback={null} priority />\n      ) : (\n"
      "        <OmniFlowBot\n          label={home.hero.visualLabel}\n          copy={home.hero.bot}\n"
      "          primary={primary}\n          secondary={secondary}\n          more={more}\n        />" in VISUAL,
      "asset or bot")
check("visual reads honest channels", "const { primary, secondary, more } = pickBotChannels(integrations);" in VISUAL
      and "channels={" not in VISUAL, "statuses")
check("product cards retired", "heroCards" not in VISUAL and "lucide-react" not in VISUAL
      and not os.path.exists(ROOT + "app/components/hero/BotVisualPlaceholder.tsx"), "replaced by the bot")
AIV = read("app/components/hero/AIVisual.tsx")
check("ai visual slot has no overlay children", "children" not in AIV, "unused prop removed")
SECTIONS = read("lib/marketing/sections.ts")
check("bot copy defaults (cms)", all(k in SECTIONS for k in ('    greeting: "Hi, I\'m OmniFlow.",', "    intro: ", "    channels: ",
                                                             "    soon: ", '    connected: "All connected in one place.",', '    soonLabel: "Soon",',
                                                             '    display: "OmniFlow",')), "home_sections.hero.bot")
check("dead hero copy gone", "visualStatus" not in SECTIONS and "HERO_VISUAL_CARDS" not in SECTIONS
      and "heroCards" not in read("lib/marketing/copy.ts"), "no orphans")
FINAL = read("app/components/FinalCTA.tsx")
check("final cta slot untouched", "<AIVisual asset={finalCtaVisualAsset} fallback={null}" in FINAL, "other user")

print("== performance ==")

def rule(name):
    return "\n".join(re.findall(r"(?m)^%s(?:,\n[^{]*)? \{(.*?)\n\}" % re.escape(name), CSS, re.S))


banned = [lib for lib in ("three", "@react-three", "lottie", "gsap", "framer-motion", "motion/react", "<canvas",
                          "<video", ".gif", "webgl", "getContext(") if lib in ALL]
check("no heavy runtime", not banned, banned or "svg + css")
check("no react state in the loop", "useState" not in MOTION and "setState" not in MOTION, "refs + css vars")
check("css vars written", 'el.style.setProperty("--lx", x.toFixed(3));' in MOTION, "--lx/--ly")
check("one raf, self-stopping", MOTION.count("requestAnimationFrame(tick)") == 2
      and "if (Math.abs(tx - x) + Math.abs(ty - y) + Math.abs(tp - p) > 0.002) raf = requestAnimationFrame(tick);" in MOTION, "settles")
check("cursor closeness drives the light", 'el.style.setProperty("--lp", p.toFixed(3));' in MOTION
      and "const tp = pointer.near ? Math.max(0, 1 - Math.hypot(dx, dy) / NEAR) : 0;" in MOTION
      and "near: false };" in MOTION, "near = stronger, far = neutral")
check("tracking gated", 'matchMedia("(hover: hover) and (pointer: fine)").matches' in MOTION
      and 'if (event.pointerType !== "mouse") return;' in MOTION, "desktop only")
check("reduced motion skips js", 'matchMedia("(prefers-reduced-motion: reduce)").matches) return;' in MOTION, "a11y")
check("offscreen pause", "new IntersectionObserver(" in MOTION and 'el.toggleAttribute("data-paused", !visible);' in MOTION
      and ".root[data-paused] *,\n.root[data-paused] *::after {\n  animation-play-state: paused;" in CSS, "io")
adds = re.findall(r"addEventListener\(\"(\w+)\"", MOTION)
removes = re.findall(r"removeEventListener\(\"(\w+)\"", MOTION)
check("listeners cleaned up", sorted(adds) == sorted(removes) and len(adds) == 4, adds)
check("listeners passive", MOTION.count("{ passive: true }") == 3, "scroll never blocked")
check("no preventDefault", "preventDefault" not in MOTION, "touch scroll free")

frames = re.findall(r"@keyframes ([\w-]+) \{(.*?)\n\}", CSS, re.S)
props = sorted({p for _, body in frames for p in re.findall(r"^\s+([a-z-]+):", body, re.M)})
check("keyframes: transform/opacity only", props == ["animation-timing-function", "opacity", "transform"] and len(frames) >= 15, props)
beziers = re.findall(r"animation-timing-function: cubic-bezier\(([^)]*)\);", CSS)
curves = [tuple(map(float, b.split(", "))) for b in beziers]
check("pass-through timing never overshoots", len(curves) >= 20 and len(beziers) == CSS.count("animation-timing-function")
      and all(x1 == 0.333 and x2 == 0.667 and 0 <= y1 <= 1 and 0 <= y2 <= 1 for x1, y1, x2, y2 in curves), "monotone slopes")
used = set(re.findall(r"animation: (bot-[\w-]+)", CSS)) | set(re.findall(r"(?m)^    (bot-[\w-]+) ", CSS))
check("every keyframe used", {n for n, _ in frames} == used, sorted({n for n, _ in frames} ^ used))
check("no transitions, will-change only on cursor planes", "transition" not in CSS and CSS.count("will-change: transform;") == 4
      and all("will-change: transform;" in rule(n) for n in (".depth", ".lightSpot", ".head", ".follow")),
      "animations + 4 raster-once planes")
check("no layout box changes in motion", not re.search(r"@keyframes[^}]*(width|height|top|left|margin)", CSS), "no cls")
check("square reserved box", "  aspect-ratio: 1;\n  container-type: inline-size;" in CSS, "no cls")

print("== tokens / look ==")

code = re.sub(r'path: "[^"]*"', "", VIEW + MOTION + CSS + CHANNELS)
check("no hardcoded colours", not re.findall(r"#[0-9a-fA-F]{3,8}\b|rgba?\(|hsla?\(", code),
      re.findall(r"#[0-9a-fA-F]{3,8}\b|rgba?\(", code)[:4])
for token in ("--color-surface", "--color-soft", "--color-line", "--color-line-2", "--color-ink", "--color-ink-3", "--color-brand"):
    check("token " + token, "var(%s)" % token in CSS, "theme")
check("token shell + platform", "--bot-shell: var(--color-surface);" in CSS and "--bot-shade: var(--color-soft);" in CSS, "theme")
check("chest display", "className={s.display}" in VISUAL_BOT and "{display}" in VISUAL_BOT and "<BotVisual display={copy.display} />" in CONTAINER
      and "steps(6, end)" in CSS and "textLength: Math.min(15.4, display.length * 2.1)" in VISUAL_BOT, "digital meter, fitted to the panel")
check("robot in its own file", "<Depth z={" not in CONTAINER and "const LAYERS = {" in VISUAL_BOT and "const LAYERS" not in CONTAINER
      and '"use client"' not in VISUAL_BOT and "export default function BotVisual({ display }: { display: string })" in VISUAL_BOT, "swappable asset")
loops = re.findall(r"animation: (bot-[\w-]+) 12s [^;]* infinite", CSS)
check("intro loops every 12s", "const RIGHT_AT = 5;" in CONTAINER and "const LEFT_AT = 7;" in CONTAINER and "const STEP = 0.3;" in CONTAINER
      and sorted(loops) == sorted(["bot-say-%d" % i for i in range(1, 6)] + ["bot-lean", "bot-head", "bot-arm-l", "bot-arm-r", "bot-fore-l", "bot-fore-r",
                                                                         "bot-hand-l", "bot-hand-r", "bot-glance", "bot-smile",
                                                                         "bot-palm-r", "bot-grip-r"])
      and "bot-ping 12s var(--bot-spring) var(--d) infinite;" in CSS and "9.6s" not in CSS and "INTRO_MS" not in MOTION, loops)
say5 = re.search(r"@keyframes bot-say-5 \{(.*?)\n\}", CSS, re.S).group(1)
say1 = re.search(r"@keyframes bot-say-1 \{(.*?)\n\}", CSS, re.S).group(1)
check("loop seam: no empty bubble", "99.58%,\n  100% {\n    opacity: 0;" in say5 and "0%,\n  0.42% {" in say1 and "2.92%," in say1, "0.1s cross-over")
check("closing line rests", "copy.connected].filter(Boolean)" in CONTAINER and "{copy.connected}</p>" in CONTAINER
      and "@keyframes bot-say-5" in CSS and ".root[data-nointro] .line:not(.line5) {\n  display: none;" in CSS, "all connected in one place")
kf = {n: re.search(r"@keyframes bot-%s \{(.*?)\n\}" % n, CSS, re.S).group(1) for n in
      ("arm-r", "fore-r", "hand-r", "arm-l", "fore-l", "hand-l", "head", "lean", "glance", "smile")}
check("human arms: joint chains", all("transform-origin: %s;" % o in rule(n) for n, o in (
          (".foreL", "16.46% 52.22%"), (".foreR", "84.11% 52.16%"), (".handL", "11.33% 63.66%"), (".handR", "88.77% 63.66%")))
      and "joints: [s.armR, s.foreR, s.handR]" in VISUAL_BOT and "joints.reduceRight<ReactNode>(" in VISUAL_BOT, "shoulder > elbow > wrist")
def stops(block):
    """keyframe block -> {percent: value} (merged stops expanded)."""
    out = {}
    for sel, val in re.findall(r"((?:\s*[\d.]+%,?)+) \{\n    (?:transform|opacity): ([^;]+);", block):
        for p in re.findall(r"([\d.]+)%", sel):
            out[float(p)] = val
    return out


def angles(block):
    return [float(a) for a in re.findall(r"rotate\((-?[\d.]+)deg\)", block)]


def held(frames, at):
    """value at a stop; merged stops hold their value in between."""
    return frames[max(p for p in frames if p <= at)]


palm_r, grip_r = stops(re.search(r"@keyframes bot-palm-r \{(.*?)\n\}", CSS, re.S).group(1)), stops(re.search(r"@keyframes bot-grip-r \{(.*?)\n\}", CSS, re.S).group(1))
pc = lambda t: round(t / 12 * 100, 2)
check("front wave: open palm to the viewer", "rotate(-61deg)" in kf["arm-r"] and kf["fore-r"].count("rotate(-112deg)") >= 2
      and kf["hand-r"].count("rotate(12deg)") >= 2 and "rotate(-10deg)" in kf["hand-r"] and "rotate(-8deg)" in kf["hand-r"]
      and all(held(palm_r, pc(t)) == "1" and held(grip_r, pc(t)) == "0" for t in (0.95, 1.2, 1.7, 2.4))
      and all(held(palm_r, pc(t)) == "0" and held(grip_r, pc(t)) == "1" for t in (0.5, 0.8)), "palm opens once the forearm is up")
check("gestures face the viewer, no side pointing", min(angles(kf["arm-r"])) >= -62 and max(angles(kf["arm-l"])) <= 36
      and max(map(abs, angles(kf["head"]))) <= 5 and "translate(0.4%, 0%) rotate(2.5deg)" in kf["head"] and "translate(-0.4%, 0%) rotate(-2.5deg)" in kf["head"]
      and "translate(2px, 0.4px)" in kf["glance"] and "rotate(40deg) scale(1, 0.85)" in kf["fore-r"] and "rotate(-40deg) scale(1, 0.85)" in kf["fore-l"],
      "palms out, head to the viewer")
def k_of(value):
    m = re.search(r"scale\(1, ([\d.]+)\)", value)
    return float(m.group(1)) if m else 1.0


fore_hand = [(k_of(v), k_of(held(stops(kf["hand-" + side]), p))) for side in "rl" for p, v in stops(kf["fore-" + side]).items()]
squash = len(fore_hand) > 40 and all(abs(f * h - 1) < 0.002 for f, h in fore_hand)
check("foreshortening keeps the hand's shape", squash and "scale(1, 0.82)" in kf["fore-r"] and "scale(1, 1.22) rotate(-10deg)" in kf["hand-r"], "wrist undoes the squash")
check("asymmetric arms + anticipation", kf["arm-r"] != kf["arm-l"].replace("rotate(", "rotate(-") and stops(kf["arm-r"]).get(1.67) == "rotate(3deg)"
      and stops(kf["fore-r"]).get(1.67) == "rotate(4deg) scale(1, 1)" and stops(kf["arm-r"]).get(28.75) == "rotate(-12deg)"
      and stops(kf["arm-l"]).get(26.67) == "rotate(12deg)", "the arms explain out of step")
check("head + face + body language", "translate(0%, -0.4%) rotate(5deg)" in kf["head"] and "translate(0%, 0.8%)" in kf["head"]
      and "scale(1.18, 1.25)" in kf["smile"] and "rotate(-0.8deg)" in kf["lean"] and "translateY(-0.5%)" in kf["lean"]
      and "--bot-swing: cubic-bezier(0.37, 0, 0.23, 1);" in CSS, "confident intro")
motion_src = ROOT + "tools/bot-render/motion.py"
spec = __import__("importlib.util").util.spec_from_file_location("bot_motion", motion_src)
motion = __import__("importlib.util").util.module_from_spec(spec)
spec.loader.exec_module(motion)
block = re.search(re.escape(motion.BEGIN) + r"\n(.*?)\n" + re.escape(motion.END), CSS, re.S)
check("timeline generated by motion.py", block is not None and block.group(1) == motion.build() and motion.LOOP == 12.0, "CSS == motion.py output")


def origin(name):
    return tuple(float(v) for v in re.search(r"transform-origin: ([\d.]+)% ([\d.]+)%;", rule(name)).groups())


def bezier(spec):
    x1, y1, x2, y2 = spec

    def ease(x):
        lo, hi = 0.0, 1.0
        for _ in range(40):
            t = (lo + hi) / 2
            if 3 * (1 - t) ** 2 * t * x1 + 3 * (1 - t) * t * t * x2 + t ** 3 < x:
                lo = t
            else:
                hi = t
        t = (lo + hi) / 2
        return 3 * (1 - t) ** 2 * t * y1 + 3 * (1 - t) * t * t * y2 + t ** 3
    return ease


SWING = bezier((0.37, 0, 0.23, 1))


def simulate(side, poses):
    """fingertip speed (canvas heights / s), sideways forearm length, hand stretch (forearm k and wrist 1/k interpolate apart),
    and how far the OPEN palm's fingers ever point sideways (|sin| of the hand direction)."""
    import math
    W, H = 560, 846
    suf = side.upper()
    S, E, Wr = [(x / 100 * W, y / 100 * H) for x, y in (origin(".arm" + suf), origin(".fore" + suf), origin(".hand" + suf))]
    poses = [(0, *motion.REST)] + list(poses) + [(motion.LOOP, *motion.REST)]
    ts = [p[0] for p in poses]
    timings = getattr(motion, "timings", lambda ts, vs: {})  # before 253 every segment eased on its own
    shoulder, elbow = timings(ts, [p[1] for p in poses]), timings(ts, [p[2] for p in poses])
    curve = lambda tim, t0: bezier(tuple(map(float, tim[t0][13:-1].split(", ")))) if t0 in tim else SWING
    rot = lambda v, d: (v[0] * math.cos(math.radians(d)) - v[1] * math.sin(math.radians(d)), v[0] * math.sin(math.radians(d)) + v[1] * math.cos(math.radians(d)))
    about = lambda o, p, fn: (lambda v: (o[0] + v[0], o[1] + v[1]))(fn((p[0] - o[0], p[1] - o[1])))
    speed = sideways = stretch = palm_side = 0.0
    windows = motion.PALM.get(side, [])
    fade = getattr(motion, "FADE", 0)
    prev = None
    for i in range(int(motion.LOOP * 120) + 1):
        t = i / 120
        for (t0, *a), (t1, *b) in zip(poses, poses[1:]):
            if t0 <= t <= t1:
                x = (t - t0) / (t1 - t0)
                us, ue = curve(shoulder, t0)(x), curve(elbow, t0)(x)
                s_, f, h, k = a[0] + (b[0] - a[0]) * us, a[1] + (b[1] - a[1]) * ue, a[2] + (b[2] - a[2]) * ue, a[3] + (b[3] - a[3]) * ue
                stretch = max(stretch, abs(k * (1 / a[3] + (1 / b[3] - 1 / a[3]) * ue) - 1))
                break
        world = lambda p: about(S, about(E, about(Wr, p, lambda v: (lambda w: (w[0], w[1] / k))(rot(v, h))), lambda v: rot((v[0], v[1] * k), f)), lambda v: rot(v, s_))
        tip, e, w = world((Wr[0], Wr[1] + 0.09 * H)), world(E), world(Wr)
        ang = abs(math.degrees(math.atan2(-(w[0] - e[0]), w[1] - e[1])))
        if 40 < ang < 140:
            sideways = max(sideways, k * abs(math.sin(math.radians(ang))))
        if any(a + fade / 2 <= t <= c + fade / 2 for a, c in windows):
            palm_side = max(palm_side, abs(math.sin(math.atan2(tip[0] - w[0], tip[1] - w[1]))))
        if prev:
            speed = max(speed, math.dist(tip, prev) * 120 / H)
        prev = tip
    return speed, sideways, stretch, palm_side


sim = {side: simulate(side, poses) for side, poses in (("r", motion.ARM_R), ("l", motion.ARM_L))}
check("arms move smoothly (no whip)", all(v[0] < 1.3 for v in sim.values()), {k: round(v[0], 2) for k, v in sim.items()})
check("no sideways reach: the hand comes toward the viewer", all(v[1] <= 0.6 for v in sim.values()), {k: round(v[1], 2) for k, v in sim.items()})
check("hand keeps its shape while moving", all(v[2] < 0.06 for v in sim.values()), {k: round(v[2], 3) for k, v in sim.items()})
check("open palm never points to the side", all(v[3] <= 0.8 for v in sim.values()), {k: round(v[3], 2) for k, v in sim.items()})
holds = [(side, t) for side, arms in (("r", motion.ARM_R), ("l", motion.ARM_L)) for j in (1, 2)
         for (_, *a), (t, *b), (_, *c), (_, *d) in zip(arms, arms[1:], arms[2:], arms[3:])
         if b[j - 1] == c[j - 1] and (a[j - 1] - b[j - 1]) * (c[j - 1] - d[j - 1]) > 0]
check("no stop-and-go in the middle of a move", not holds, holds)
fore_r = re.search(r"@keyframes bot-fore-r \{(.*?)\n\}", CSS, re.S).group(1)
via = [t for (t0, _, f0, *_), (t, _, f, *_), (t1, _, f1, *_) in zip(motion.ARM_R, motion.ARM_R[1:], motion.ARM_R[2:]) if f0 > f > f1 or f0 < f < f1]
check("poses on the way are passed through, not stopped at", len(via) >= 4 and all(
          re.search(r"(?m)^  %s%%[^{]*\{[^}]*animation-timing-function" % re.escape("%g" % pc(t)), fore_r) for t in via), via)
rests = {side: [t for t, *pose in arms if tuple(pose) == motion.REST] for side, arms in (("r", motion.ARM_R), ("l", motion.ARM_L))}
wave = [t for t, s_, f, *_ in motion.ARM_R if s_ <= -55 and f <= -100]  # upper arm out, forearm up
opened = [i / 20 for i in range(int(motion.LOOP * 20)) if held(palm_r, pc(i / 20)) != "0" or held(grip_r, pc(i / 20)) != "1"]
check("hands relaxed, palms to the body; only the waving hand opens", list(motion.PALM) == ["r"] and len(motion.PALM["r"]) == 1
      and all(held(palm_r, pc(t)) == "0" and held(grip_r, pc(t)) == "1" for t in rests["r"])
      and bool(wave) and min(wave) - 0.4 <= motion.PALM["r"][0][0] and motion.PALM["r"][0][1] <= max(wave) + 0.5
      and all(motion.PALM["r"][0][0] <= t <= motion.PALM["r"][0][1] + motion.FADE for t in opened)
      and held(grip_r, pc(motion.PALM["r"][0][0])) == "1" and held(grip_r, pc(motion.PALM["r"][0][0] + motion.FADE)) == "0"
      and held(grip_r, pc(motion.PALM["r"][0][1] + motion.FADE)) == "1"
      and not re.search(r"bot-(?:palm|grip)-l\b|\.(?:palmL|gripL)\b", CSS) and "palm-l" not in VISUAL_BOT,
      (motion.PALM, opened[:1] + opened[-1:]))
box_r = re.search(r'src: "/bot/omniflow-bot-palm-r.webp".*?box: \[([-\d., ]+)\]', VISUAL_BOT).group(1)
unfold = lambda box, wrist: "%.2f%% %.2f%%" % ((wrist[0] - box[0]) / box[2] * 100, (wrist[1] - box[1]) / box[3] * 100)
bx_r = [float(v) for v in box_r.split(", ")]
check("palm unfolds from the wrist, quickly", getattr(motion, "FADE", 1) <= 0.12 and "transform: scale(0.85);" in CSS
      and "transform-origin: %s;" % unfold(bx_r, origin(".handR")) in rule(".palmR"), "no double hand")
blink = re.search(r"@keyframes bot-blink \{(.*?)\n\}", CSS, re.S).group(1)
check("blink not mechanical", "animation: bot-blink 13.7s linear 1.2s infinite;" in CSS and blink.count("scaleY(0.1)") == 4, "single, double, single")
check("intro can be skipped", 'data-nointro={intro ? undefined : ""}' in CONTAINER
      and ".root[data-nointro] :is(.speech, .figure, .line, .glance, .node, .links line, .smile, .display, .lean, .foreL, .foreR, .handL, .handR, .palmR, .gripR) {\n  animation: none;" in CSS
      and ".palm {\n  position: absolute;\n  opacity: 0;" in CSS
      and ".root[data-nointro] .nod {\n  animation: bot-nod 8s ease-in-out infinite;" in CSS
      and "born" not in MOTION, "intro={false}")
check("touch reaction optional", "tap={interactive && animated}" in CONTAINER
      and 'if (tap && el.hasAttribute("data-nointro")) el.addEventListener("click", onTap, { passive: true });' in MOTION, "interactive={false}")
fills = sorted(set(re.findall(r'fill: "var\(--(bot-[\w-]+)\)"', VIEW) + re.findall(r"fill: var\(--(bot-[\w-]+)\)", CSS)))
undefined = [f for f in fills if "  --%s:" % f not in CSS]
dangling = [u for u in re.findall(r"--bot-[\w-]+: url\(#([\w-]+)\)", CSS) if 'id="%s"' % u not in VIEW]
check("every fill token defined", len(fills) >= 6 and not undefined and not dangling, undefined or dangling or "%d tokens" % len(fills))
check("lighter on touch screens", "@media (hover: none) {\n  .light,\n  .bubble::after {\n    display: none;\n  }\n\n  .bubble,\n  .pulse,\n  .bar {\n    animation: none;" in CSS,
      "no cursor light on touch")
visor = (29.37, 70.93)
travel = 1.8 + 1.4 + 2.0  # eye look + face turn + intro glance, canvas units
reach = [cx + side * (4.4 + 2.4 / 2 + travel) for cx, side in ((40.4, -1), (60, 1))]
check("eyes stay in the visor", 'r="4.4"' in VIEW and "{[40.4, 60].map((cx)" in VIEW
      and "transform: translate(calc(var(--ex, 0) * 1.8px), calc(var(--ey, 0) * 1.4px));" in rule(".look")
      and "transform: translate(calc(var(--lx, 0) * 1.4px), calc(var(--ly, 0) * 0.9px));" in rule(".faceTurn")
      and "translate(2px, 0.4px)" in CSS and "translate(2.4px" not in CSS
      and "stroke-width: 2.4;" in rule(".eyeGlow") and visor[0] < reach[0] and reach[1] < visor[1], reach)
check("eyes lead, head follows", "const EASE_EYES = 0.2;" in MOTION and "const EASE = 0.08;" in MOTION
      and 'el.style.setProperty("--ex", ex.toFixed(3));' in MOTION and "<g className={s.faceTurn}>" in VISUAL_BOT
      and "rotate(calc(var(--lx, 0) * 5deg))" in rule(".head") and "transform: rotate(calc(var(--lx, 0) * 1.2deg));" in rule(".follow"),
      "natural tracking")
check("brand accent, not sky blue", "--bot-accent: var(--color-brand);" in CSS
      and "--bot-accent-light: color-mix(in srgb, var(--color-brand) 48%, var(--color-surface));" in CSS, "owner pick")
check("official logos (cc0/mit)", "Simple Icons 16.34 (CC0" in CHANNELS and "Bootstrap Icons 1.13 (MIT" in CHANNELS
      and CHANNELS.count('path: "M') == 8 and CHANNELS.count('viewBox: "0 0 16 16"') == 1, "brand marks")
check("both arcs", all('{ id: "%s", name: ' % i in CHANNELS for i in ("whatsapp", "instagram", "messenger", "tiktok", "x", "telegram", "linkedin")),
      "4 + 4 logos")
check("facebook via messenger", '{ id: "facebook", name: "Facebook", integration: "messenger",' in CHANNELS, "honest")
check("soon only on the left arc", 'if (!source || (offeredOnly && source.status === "soon")) return [];' in CHANNELS
      and 'soon: source.status === "soon",' in CHANNELS and "const primary = nodes(PRIMARY, true);" in CHANNELS
      and "const secondary = nodes(SECONDARY, false);" in CHANNELS, "honest, status-driven")
check("soon badge from cms", "{node.channel?.soon ? <span className={s.badge}>{copy.soonLabel}</span> : null}" in VIEW, "copy")

print("== 3d model ==")

LAYER_FILES = ["omniflow-bot-body.webp", "omniflow-bot-head.webp"] + ["omniflow-bot-%s-%s.webp" % (seg, side)
                                                                     for side in "lr" for seg in ("upper", "fore", "hand")]


def webp_size(path):
    data = open(path, "rb").read()
    if data[:4] != b"RIFF" or data[8:12] != b"WEBP" or data[12:16] != b"VP8X" or not data[20] & 0x10:
        return None  # need the extended format with alpha
    return (1 + int.from_bytes(data[24:27], "little"), 1 + int.from_bytes(data[27:30], "little")), len(data)


layers = [webp_size(ROOT + "public/bot/" + f) if os.path.exists(ROOT + "public/bot/" + f) else None for f in LAYER_FILES]
check("pre-rendered 3d layers", all(l and l[0] == (560, 846) for l in layers) and VIEW.count("<Layer src={LAYERS.") == 2
      and "<Layer src={layers[i]} />" in VISUAL_BOT and VIEW.count("<Arm {...ARMS.") == 2
      and not glob.glob(ROOT + "public/bot/omniflow-bot-arm-*.webp")
      and all('"/bot/%s"' % f in VISUAL_BOT for f in LAYER_FILES) and "const SIZE = { width: 560, height: 846 };" in VISUAL_BOT
      and "aspect-ratio: 560 / 846;" in rule(".figure"), layers)
total = sum(l[1] for l in layers if l)
palm = webp_size(ROOT + "public/bot/omniflow-bot-palm-r.webp") if os.path.exists(ROOT + "public/bot/omniflow-bot-palm-r.webp") else None
check("waving palm: own box on the wrist", palm and palm[0] == (142, 161)
      and 'size: { width: 142, height: 161 }, box: [81.25, 61.58, 25.36, 19.03]' in VISUAL_BOT and VISUAL_BOT.count("palm: {") == 1
      and "{inner || !palm ? <Layer src={layers[i]} /> : <Hand src={layers[i]} palm={palm} />}" in VISUAL_BOT
      and "<Layer src={palm.src} size={palm.size} />" in VISUAL_BOT, palm)


def hand_size():
    """open palm vs the arm it sits on (px of the 560 canvas): palm + fingers width / forearm cuff width,
    and hand length / relaxed hand length. A real open hand is about as wide as the wrist."""
    try:
        import numpy as np
        from PIL import Image
    except ImportError:
        return None
    mask = lambda f: np.array(Image.open(ROOT + "public/bot/" + f).convert("RGBA"))[..., 3] > 8
    span = lambda m: [r.nonzero()[0][-1] - r.nonzero()[0][0] + 1 for r in m if r.any()]
    palm_rows, fore, grip = span(mask("omniflow-bot-palm-r.webp")), mask("omniflow-bot-fore-r.webp"), mask("omniflow-bot-hand-r.webp")
    cuff = max(span(fore[int(0.6 * 846):int(0.64 * 846)]))
    grip_rows = np.nonzero(grip.any(axis=1))[0]
    return round(max(palm_rows[len(palm_rows) // 2:]) / cuff, 2), round(len(palm_rows) / (grip_rows[-1] - grip_rows[0] + 1), 2)


size = hand_size()
check("open palm is a normal hand, not a big splayed one", size is not None and size[0] <= 1.15 and size[1] <= 1.15, size)
total += palm[1] if palm else 0
check("layers stay light", all(l and l[1] < 40000 for l in layers) and total < 110000, "%d bytes" % total)
split = read("tools/bot-render/split.py")
check("arm cuts close at the joints", "BAND = 16" in split and "(past_elbow > -8)" in split and "(past_wrist <= 6)" in split
      and "(upper | fore | hand).sum() == arm.sum()" in split, "elbow band socket + wrist overlap")
check("render source ships", all(os.path.exists(ROOT + "tools/bot-render/" + f) for f in ("key.py", "split.py", "motion.py", "omniflow-bot-render.webp",
                                                                                     "omniflow-bot-render-wave.webp"))
      and all(f in read("tools/bot-render/.gitignore") for f in ("robot_rgba.png", "wave_rgba.png"))
      and '("omniflow-bot-render-wave.webp", "wave_rgba.png")' in read("tools/bot-render/key.py")
      and "palms_rgba" not in read("tools/bot-render/key.py") + split and "zoom = " in split and "ring_top(" in split,
      "re-cut the layers; intermediates ignored")
small = re.search(r"@media \(max-width: 639px\) \{(.*?)\n\}\n", CSS, re.S)
check("phones: taller stage, bigger robot, readable lines", small is not None and "aspect-ratio: 5 / 6;" in small.group(1)
      and "left: 25%;\n    top: 21.5%;\n    width: 50%;" in small.group(1) and "font-size: clamp(12.5px, 3.9cqw, 15px);" in small.group(1)
      and "width: clamp(34px, 12cqw, 52px);" in small.group(1)
      and "@media (min-width: 640px) and (max-width: 1023px) {\n  .figure {\n    left: 27%;\n    top: 20%;\n    width: 46%;" in CSS, "responsive")
check("depth parallax", "transform: translate(calc(var(--lx, 0) * var(--z) * 0.5cqw), calc(var(--ly, 0) * var(--z) * 0.25cqw));" in rule(".depth")
      and VIEW.count("<Depth z={") == 5, "nearer planes travel further")
resample = [w for w in ("preserve-3d", "rotateY", "rotateX", "perspective", "translateZ") if w in CSS]
check("render stays sharp", not resample, resample or "no 3d re-sampling of the image")
check("pivots match the render", "transform-origin: 50.2% 32.4%;" in rule(".head") and "transform-origin: 25.84% 40.61%;" in rule(".armL")
      and "transform-origin: 74.88% 40.59%;" in rule(".armR"), "neck + shoulders")
check("cursor light per layer", "maskImage: mask, WebkitMaskImage: mask" in VISUAL_BOT and "mix-blend-mode: soft-light;" in rule(".light")
      and "opacity: calc(0.3 + var(--lp, 0) * 0.6);" in rule(".light")
      and "transform: translate(calc(var(--lx, 0) * 20%), calc(var(--ly, 0) * 18%));" in rule(".lightSpot"), "moving key light")
check("light reaches the bubbles", "transform: translate(calc(var(--lx, 0) * -22%), calc(var(--ly, 0) * -22%));" in rule(".bubble::after")
      and "opacity: calc(0.2 + var(--lp, 0) * 0.5);" in rule(".bubble::after"), "same light")
check("standing, not floating", "bot-float" not in CSS and "@keyframes bot-breathe" in CSS and "@keyframes bot-pulse" in CSS
      and "top: 88.7%;" in rule(".platform"), "on the platform")
check("light platform", "className={s.disc}" in VIEW and "s.pulse" in VIEW and 'fill: "var(--bot-floor-shadow)"' in VIEW, "surface")
emoji = [c for c in ALL if ord(c) > 0x2000]
check("no emoji code points", not emoji, emoji[:3])

print("== accessibility ==")

check("one labelled image", 'role="img"' in VIEW and "aria-label={[label, ...spoken].map(sentence).join(" + '" ")}' in VIEW, "a11y")
check("decoration hidden", VISUAL_BOT.count('aria-hidden focusable="false"') == 3 and 'alt=""' in VISUAL_BOT, "decorative")
check("reduced motion = final pose", "@media (prefers-reduced-motion: reduce) {\n  .root *,\n  .root *::after {\n    animation: none !important;" in CSS
      and re.search(r"\.line1 \{[^}]*opacity: 0;", CSS) and re.search(r"\.line2 \{[^}]*opacity: 0;", CSS)
      and re.search(r"\.line3 \{[^}]*opacity: 0;", CSS) and re.search(r"\.line4 \{[^}]*opacity: 0;", CSS)
      and not re.search(r"\.line5 \{[^}]*opacity: 0;", CSS), "calm pose")
check("still mode", ".root[data-static] *," in CSS and 'data-static={animated ? undefined : ""}' in VIEW, "animated=false")
check("nodes not interactive", re.search(r"\.node \{[^}]*pointer-events: none;", CSS) is not None, "decorative")
check("tap wave only without the intro", '"pointerdown"' not in MOTION and 'el.hasAttribute("data-nointro")) el.addEventListener("click", onTap' in MOTION
      and '(event as PointerEvent).pointerType === "mouse" || waveTimer) return;' in MOTION and ".waving .tap {" in CSS,
      "never on top of the intro arms, never on a scroll touch")

print("== functional (real tsx) ==")

ts_mod = None
for base in (ROOT, REPO):
    candidate = os.path.join(base, "node_modules", "typescript")
    if os.path.isdir(candidate):
        ts_mod = candidate
        break
node = shutil.which("node")
if not (node and ts_mod):
    check("functional harness", True, "skipped: node/typescript not available")
else:
    env = dict(os.environ, NODE_PATH=os.path.dirname(ts_mod))
    out = subprocess.run([node, os.path.join(HERE, "hero_bot_harness.cjs"), ROOT, ts_mod],
                         capture_output=True, text=True, timeout=120, env=env)
    lines = [line for line in out.stdout.splitlines() if line.startswith(("PASS ", "FAIL "))]
    check("harness ran", out.returncode == 0 and len(lines) >= 29, out.stderr[-300:] or "%d cases" % len(lines))
    for line in lines:
        status, _, name = line.partition(" ")
        check("fn " + name[:60], status == "PASS", name)

summary("hero_bot")
