"""Tests for batches 247-252: the hero OmniFlowBot.

A pre-rendered 3D robot (250; 251: arms as shoulder > elbow > wrist
chains, a looping 12s intro with head / face / body language, eyes that
lead the head; 252: open palms from a second render for a front wave and
gestures toward the viewer, timeline generated by motion.py, a taller
stage and bigger robot on phones; WebP layers on one canvas in
public/bot, made by tools/bot-render) with live token-coloured overlays
(LED eyes, smile, chest meter), depth parallax + a per-layer cursor light,
standing on a light platform, with a CSS intro timeline (9.6s), the robot
in its own BotVisual file (249),
two channel arcs from the honest integrations list (Soon badge
for upcoming channels) and one small client
island (cursor tracking via CSS vars + rAF, offscreen pause, tap wave).
Static pins for the performance / token / accessibility laws, plus the
functional harness (hero_bot_harness.cjs: real TSX rendered with
react-dom/server).
"""
import glob
import os
import re
import shutil
import subprocess

import test_lib
from test_lib import check, summary

ROOT = "/tmp/p13/Omniflow/"
REPO = "/home/user/Omniflow/"
HERE = os.path.dirname(os.path.abspath(__file__))
BOT = "app/components/OmniFlowBot/"


def read(path):
    return open(ROOT + path, encoding="utf8").read()


print("== isolation ==")

FILES = sorted(os.path.basename(p) for p in glob.glob(ROOT + BOT + "*") if not p.endswith(".bak"))  # patcher backups are git-ignored
check("bot files", FILES == ["BotMotion.tsx", "BotVisual.tsx", "OmniFlowBot.module.css", "OmniFlowBot.tsx", "botChannels.ts"], FILES)
CONTAINER = read(BOT + "OmniFlowBot.tsx")
VISUAL_BOT = read(BOT + "BotVisual.tsx")
VIEW = CONTAINER + VISUAL_BOT
MOTION = read(BOT + "BotMotion.tsx")
CSS = read(BOT + "OmniFlowBot.module.css")
CHANNELS = read(BOT + "botChannels.ts")
ALL = VIEW + MOTION + CSS + CHANNELS
check("bot is a server component", '"use client"' not in VIEW and "useState" not in VIEW and "useEffect" not in VIEW, "no client code")
check("one client island", MOTION.startswith('"use client";') and '"use client"' not in CHANNELS, "BotMotion only")
check("props api", all(p in CONTAINER for p in ("intro = true,", "interactive = true,", "socialBubbles = true,", "cursorTracking = true,", "animated = true,",
                                             "label: string;", "copy: OmniFlowBotCopy;")), "props")
check("bot knows no cms", "getCopy" not in VIEW and "lib/marketing" not in VIEW and "lib/marketing" not in CHANNELS, "data via props")

HERO = read("app/components/Hero.tsx")
check("hero stays dumb", "<HeroVisual />" in HERO and "OmniFlowBot" not in HERO, "slot only")
VISUAL = read("app/components/hero/HeroVisual.tsx")
check("visual slot swap", "{heroVisualAsset ? (\n        <AIVisual asset={heroVisualAsset} fallback={null} priority />\n      ) : (\n"
      "        <OmniFlowBot\n          label={home.hero.visualLabel}\n          copy={home.hero.bot}\n"
      "          primary={primary}\n          secondary={secondary}\n          more={more}\n        />" in VISUAL,
      "asset or bot")
check("visual reads honest channels", "const { primary, secondary, more } = pickBotChannels(integrations);" in VISUAL
      and "channels={" not in VISUAL, "statuses")
check("product cards retired", "heroCards" not in VISUAL and "lucide-react" not in VISUAL
      and not os.path.exists(ROOT + "app/components/hero/BotVisualPlaceholder.tsx"), "replaced by the bot")
AIV = read("app/components/hero/AIVisual.tsx")
check("ai visual slot has no overlay children", "children" not in AIV, "unused prop removed")
SECTIONS = read("lib/marketing/sections.ts")
check("bot copy defaults (cms)", all(k in SECTIONS for k in ('    greeting: "Hi, I\'m OmniFlow.",', "    intro: ", "    channels: ",
                                                             "    soon: ", '    connected: "All connected in one place.",', '    soonLabel: "Soon",',
                                                             '    display: "OmniFlow",')), "home_sections.hero.bot")
check("dead hero copy gone", "visualStatus" not in SECTIONS and "HERO_VISUAL_CARDS" not in SECTIONS
      and "heroCards" not in read("lib/marketing/copy.ts"), "no orphans")
FINAL = read("app/components/FinalCTA.tsx")
check("final cta slot untouched", "<AIVisual asset={finalCtaVisualAsset} fallback={null}" in FINAL, "other user")

print("== performance ==")

def rule(name):
    return "\n".join(re.findall(r"(?m)^%s(?:,\n[^{]*)? \{(.*?)\n\}" % re.escape(name), CSS, re.S))


banned = [lib for lib in ("three", "@react-three", "lottie", "gsap", "framer-motion", "motion/react", "<canvas",
                          "<video", ".gif", "webgl", "getContext(") if lib in ALL]
check("no heavy runtime", not banned, banned or "svg + css")
check("no react state in the loop", "useState" not in MOTION and "setState" not in MOTION, "refs + css vars")
check("css vars written", 'el.style.setProperty("--lx", x.toFixed(3));' in MOTION, "--lx/--ly")
check("one raf, self-stopping", MOTION.count("requestAnimationFrame(tick)") == 2
      and "if (Math.abs(tx - x) + Math.abs(ty - y) + Math.abs(tp - p) > 0.002) raf = requestAnimationFrame(tick);" in MOTION, "settles")
check("cursor closeness drives the light", 'el.style.setProperty("--lp", p.toFixed(3));' in MOTION
      and "const tp = pointer.near ? Math.max(0, 1 - Math.hypot(dx, dy) / NEAR) : 0;" in MOTION
      and "near: false };" in MOTION, "near = stronger, far = neutral")
check("tracking gated", 'matchMedia("(hover: hover) and (pointer: fine)").matches' in MOTION
      and 'if (event.pointerType !== "mouse") return;' in MOTION, "desktop only")
check("reduced motion skips js", 'matchMedia("(prefers-reduced-motion: reduce)").matches) return;' in MOTION, "a11y")
check("offscreen pause", "new IntersectionObserver(" in MOTION and 'el.toggleAttribute("data-paused", !visible);' in MOTION
      and ".root[data-paused] *,\n.root[data-paused] *::after {\n  animation-play-state: paused;" in CSS, "io")
adds = re.findall(r"addEventListener\(\"(\w+)\"", MOTION)
removes = re.findall(r"removeEventListener\(\"(\w+)\"", MOTION)
check("listeners cleaned up", sorted(adds) == sorted(removes) and len(adds) == 4, adds)
check("listeners passive", MOTION.count("{ passive: true }") == 3, "scroll never blocked")
check("no preventDefault", "preventDefault" not in MOTION, "touch scroll free")

frames = re.findall(r"@keyframes ([\w-]+) \{(.*?)\n\}", CSS, re.S)
props = sorted({p for _, body in frames for p in re.findall(r"^\s+([a-z-]+):", body, re.M)})
check("keyframes: transform/opacity only", props == ["opacity", "transform"] and len(frames) >= 15, props)
used = set(re.findall(r"animation: (bot-[\w-]+)", CSS)) | set(re.findall(r"(?m)^    (bot-[\w-]+) ", CSS))
check("every keyframe used", {n for n, _ in frames} == used, sorted({n for n, _ in frames} ^ used))
check("no transitions, will-change only on cursor planes", "transition" not in CSS and CSS.count("will-change: transform;") == 4
      and all("will-change: transform;" in rule(n) for n in (".depth", ".lightSpot", ".head", ".follow")),
      "animations + 4 raster-once planes")
check("no layout box changes in motion", not re.search(r"@keyframes[^}]*(width|height|top|left|margin)", CSS), "no cls")
check("square reserved box", "  aspect-ratio: 1;\n  container-type: inline-size;" in CSS, "no cls")

print("== tokens / look ==")

code = re.sub(r'path: "[^"]*"', "", VIEW + MOTION + CSS + CHANNELS)
check("no hardcoded colours", not re.findall(r"#[0-9a-fA-F]{3,8}\b|rgba?\(|hsla?\(", code),
      re.findall(r"#[0-9a-fA-F]{3,8}\b|rgba?\(", code)[:4])
for token in ("--color-surface", "--color-soft", "--color-line", "--color-line-2", "--color-ink", "--color-ink-3", "--color-brand"):
    check("token " + token, "var(%s)" % token in CSS, "theme")
check("token shell + platform", "--bot-shell: var(--color-surface);" in CSS and "--bot-shade: var(--color-soft);" in CSS, "theme")
check("chest display", "className={s.display}" in VISUAL_BOT and "{display}" in VISUAL_BOT and "<BotVisual display={copy.display} />" in CONTAINER
      and "steps(6, end)" in CSS and "textLength: Math.min(15.4, display.length * 2.1)" in VISUAL_BOT, "digital meter, fitted to the panel")
check("robot in its own file", "<Depth z={" not in CONTAINER and "const LAYERS = {" in VISUAL_BOT and "const LAYERS" not in CONTAINER
      and '"use client"' not in VISUAL_BOT and "export default function BotVisual({ display }: { display: string })" in VISUAL_BOT, "swappable asset")
loops = re.findall(r"animation: (bot-[\w-]+) 12s [^;]* infinite", CSS)
check("intro loops every 12s", "const RIGHT_AT = 5;" in CONTAINER and "const LEFT_AT = 7;" in CONTAINER and "const STEP = 0.3;" in CONTAINER
      and sorted(loops) == sorted(["bot-say-%d" % i for i in range(1, 6)] + ["bot-lean", "bot-head", "bot-arm-l", "bot-arm-r", "bot-fore-l", "bot-fore-r",
                                                                         "bot-hand-l", "bot-hand-r", "bot-glance", "bot-smile",
                                                                         "bot-palm-l", "bot-palm-r", "bot-grip-l", "bot-grip-r"])
      and "bot-ping 12s var(--bot-spring) var(--d) infinite;" in CSS and "9.6s" not in CSS and "const INTRO_MS = 12000;" in MOTION, loops)
say5 = re.search(r"@keyframes bot-say-5 \{(.*?)\n\}", CSS, re.S).group(1)
say1 = re.search(r"@keyframes bot-say-1 \{(.*?)\n\}", CSS, re.S).group(1)
check("loop seam: no empty bubble", "99.58%,\n  100% {\n    opacity: 0;" in say5 and "0%,\n  0.42% {" in say1 and "2.92%," in say1, "0.1s cross-over")
check("closing line rests", "copy.connected].filter(Boolean)" in CONTAINER and "{copy.connected}</p>" in CONTAINER
      and "@keyframes bot-say-5" in CSS and ".root[data-nointro] .line:not(.line5) {\n  display: none;" in CSS, "all connected in one place")
kf = {n: re.search(r"@keyframes bot-%s \{(.*?)\n\}" % n, CSS, re.S).group(1) for n in
      ("arm-r", "fore-r", "hand-r", "arm-l", "fore-l", "hand-l", "head", "lean", "glance", "smile")}
check("human arms: joint chains", all("transform-origin: %s;" % o in rule(n) for n, o in (
          (".foreL", "16.46% 52.22%"), (".foreR", "84.11% 52.16%"), (".handL", "11.33% 63.66%"), (".handR", "88.77% 63.66%")))
      and "joints: [s.armR, s.foreR, s.handR]" in VISUAL_BOT and "joints.reduceRight<ReactNode>(" in VISUAL_BOT, "shoulder > elbow > wrist")
def stops(block):
    """keyframe block -> {percent: value} (merged stops expanded)."""
    out = {}
    for sel, val in re.findall(r"((?:\s*[\d.]+%,?)+) \{\n    (?:transform|opacity): ([^;]+);", block):
        for p in re.findall(r"([\d.]+)%", sel):
            out[float(p)] = val
    return out


def angles(block):
    return [float(a) for a in re.findall(r"rotate\((-?[\d.]+)deg\)", block)]


palm_r, grip_r = stops(re.search(r"@keyframes bot-palm-r \{(.*?)\n\}", CSS, re.S).group(1)), stops(re.search(r"@keyframes bot-grip-r \{(.*?)\n\}", CSS, re.S).group(1))
check("front wave: open palm to the viewer", "rotate(-62deg)" in kf["arm-r"] and kf["fore-r"].count("rotate(-112deg)") >= 2
      and kf["hand-r"].count("rotate(12deg)") >= 2 and "rotate(-10deg)" in kf["hand-r"] and "rotate(-8deg)" in kf["hand-r"]
      and palm_r.get(6.67) == "1" and palm_r.get(4.58) == "0" and grip_r.get(7.08) == "0" and grip_r.get(5.42) == "1", "palm open before the wave peaks")
check("gestures face the viewer, no side pointing", min(angles(kf["arm-r"])) >= -62 and max(angles(kf["arm-l"])) <= 36
      and max(map(abs, angles(kf["head"]))) <= 5 and "translate(0.4%, 0%) rotate(2.5deg)" in kf["head"] and "translate(-0.4%, 0%) rotate(-2.5deg)" in kf["head"]
      and "translate(2px, 0.4px)" in kf["glance"] and "rotate(40deg) scale(1, 0.85)" in kf["fore-r"] and "rotate(-40deg) scale(1, 0.85)" in kf["fore-l"],
      "palms out, head to the viewer")
def k_of(value):
    m = re.search(r"scale\(1, ([\d.]+)\)", value)
    return float(m.group(1)) if m else 1.0


def held(frames, at):
    """value at a stop; merged stops hold their value in between."""
    return frames[max(p for p in frames if p <= at)]


fore_hand = [(k_of(v), k_of(held(stops(kf["hand-" + side]), p))) for side in "rl" for p, v in stops(kf["fore-" + side]).items()]
squash = len(fore_hand) > 40 and all(abs(f * h - 1) < 0.002 for f, h in fore_hand)
check("foreshortening keeps the hand's shape", squash and "scale(1, 0.82)" in kf["fore-r"] and "scale(1, 1.22) rotate(-10deg)" in kf["hand-r"], "wrist undoes the squash")
check("asymmetric arms + anticipation", kf["arm-r"] != kf["arm-l"].replace("rotate(", "rotate(-") and stops(kf["arm-r"]).get(2.5) == "rotate(3deg)"
      and stops(kf["fore-r"]).get(2.5) == "rotate(4deg) scale(1, 1)" and stops(kf["arm-r"]).get(25.42) == "rotate(-12deg)"
      and stops(kf["arm-l"]).get(26.67) == "rotate(12deg)", "the left arm explains a beat later")
check("head + face + body language", "translate(0%, -0.4%) rotate(5deg)" in kf["head"] and "translate(0%, 0.8%)" in kf["head"]
      and "scale(1.18, 1.25)" in kf["smile"] and "rotate(-0.8deg)" in kf["lean"] and "translateY(-0.5%)" in kf["lean"]
      and "--bot-swing: cubic-bezier(0.37, 0, 0.23, 1);" in CSS, "confident intro")
motion_src = ROOT + "tools/bot-render/motion.py"
spec = __import__("importlib.util").util.spec_from_file_location("bot_motion", motion_src)
motion = __import__("importlib.util").util.module_from_spec(spec)
spec.loader.exec_module(motion)
block = re.search(re.escape(motion.BEGIN) + r"\n(.*?)\n" + re.escape(motion.END), CSS, re.S)
check("timeline generated by motion.py", block is not None and block.group(1) == motion.build() and motion.LOOP == 12.0, "CSS == motion.py output")
blink = re.search(r"@keyframes bot-blink \{(.*?)\n\}", CSS, re.S).group(1)
check("blink not mechanical", "animation: bot-blink 13.7s linear 1.2s infinite;" in CSS and blink.count("scaleY(0.1)") == 4, "single, double, single")
check("intro can be skipped", 'data-nointro={intro ? undefined : ""}' in CONTAINER
      and ".root[data-nointro] :is(.speech, .figure, .line, .glance, .node, .links line, .smile, .display, .lean, .foreL, .foreR, .handL, .handR, .palmL, .palmR, .gripL, .gripR) {\n  animation: none;" in CSS
      and ".palm {\n  position: absolute;\n  opacity: 0;" in CSS
      and ".root[data-nointro] .nod {\n  animation: bot-nod 8s ease-in-out infinite;" in CSS
      and 'el.hasAttribute("data-nointro") ? -INTRO_MS : performance.now()' in MOTION, "intro={false}")
check("touch reaction optional", "tap={interactive && animated}" in CONTAINER
      and 'if (tap) el.addEventListener("pointerdown", onTap, { passive: true });' in MOTION, "interactive={false}")
fills = sorted(set(re.findall(r'fill: "var\(--(bot-[\w-]+)\)"', VIEW) + re.findall(r"fill: var\(--(bot-[\w-]+)\)", CSS)))
undefined = [f for f in fills if "  --%s:" % f not in CSS]
dangling = [u for u in re.findall(r"--bot-[\w-]+: url\(#([\w-]+)\)", CSS) if 'id="%s"' % u not in VIEW]
check("every fill token defined", len(fills) >= 6 and not undefined and not dangling, undefined or dangling or "%d tokens" % len(fills))
check("lighter on touch screens", "@media (hover: none) {\n  .light,\n  .bubble::after {\n    display: none;\n  }\n\n  .bubble,\n  .pulse,\n  .bar {\n    animation: none;" in CSS,
      "no cursor light on touch")
visor = (29.37, 70.93)
travel = 1.8 + 1.4 + 2.0  # eye look + face turn + intro glance, canvas units
reach = [cx + side * (4.4 + 2.4 / 2 + travel) for cx, side in ((40.4, -1), (60, 1))]
check("eyes stay in the visor", 'r="4.4"' in VIEW and "{[40.4, 60].map((cx)" in VIEW
      and "transform: translate(calc(var(--ex, 0) * 1.8px), calc(var(--ey, 0) * 1.4px));" in rule(".look")
      and "transform: translate(calc(var(--lx, 0) * 1.4px), calc(var(--ly, 0) * 0.9px));" in rule(".faceTurn")
      and "translate(2px, 0.4px)" in CSS and "translate(2.4px" not in CSS
      and "stroke-width: 2.4;" in rule(".eyeGlow") and visor[0] < reach[0] and reach[1] < visor[1], reach)
check("eyes lead, head follows", "const EASE_EYES = 0.2;" in MOTION and "const EASE = 0.08;" in MOTION
      and 'el.style.setProperty("--ex", ex.toFixed(3));' in MOTION and "<g className={s.faceTurn}>" in VISUAL_BOT
      and "rotate(calc(var(--lx, 0) * 5deg))" in rule(".head") and "transform: rotate(calc(var(--lx, 0) * 1.2deg));" in rule(".follow"),
      "natural tracking")
check("brand accent, not sky blue", "--bot-accent: var(--color-brand);" in CSS
      and "--bot-accent-light: color-mix(in srgb, var(--color-brand) 48%, var(--color-surface));" in CSS, "owner pick")
check("official logos (cc0/mit)", "Simple Icons 16.34 (CC0" in CHANNELS and "Bootstrap Icons 1.13 (MIT" in CHANNELS
      and CHANNELS.count('path: "M') == 8 and CHANNELS.count('viewBox: "0 0 16 16"') == 1, "brand marks")
check("both arcs", all('{ id: "%s", name: ' % i in CHANNELS for i in ("whatsapp", "instagram", "messenger", "tiktok", "x", "telegram", "linkedin")),
      "4 + 4 logos")
check("facebook via messenger", '{ id: "facebook", name: "Facebook", integration: "messenger",' in CHANNELS, "honest")
check("soon only on the left arc", 'if (!source || (offeredOnly && source.status === "soon")) return [];' in CHANNELS
      and 'soon: source.status === "soon",' in CHANNELS and "const primary = nodes(PRIMARY, true);" in CHANNELS
      and "const secondary = nodes(SECONDARY, false);" in CHANNELS, "honest, status-driven")
check("soon badge from cms", "{node.channel?.soon ? <span className={s.badge}>{copy.soonLabel}</span> : null}" in VIEW, "copy")

print("== 3d model ==")

LAYER_FILES = ["omniflow-bot-body.webp", "omniflow-bot-head.webp"] + ["omniflow-bot-%s-%s.webp" % (seg, side)
                                                                     for side in "lr" for seg in ("upper", "fore", "hand")]


def webp_size(path):
    data = open(path, "rb").read()
    if data[:4] != b"RIFF" or data[8:12] != b"WEBP" or data[12:16] != b"VP8X" or not data[20] & 0x10:
        return None  # need the extended format with alpha
    return (1 + int.from_bytes(data[24:27], "little"), 1 + int.from_bytes(data[27:30], "little")), len(data)


layers = [webp_size(ROOT + "public/bot/" + f) if os.path.exists(ROOT + "public/bot/" + f) else None for f in LAYER_FILES]
check("pre-rendered 3d layers", all(l and l[0] == (560, 846) for l in layers) and VIEW.count("<Layer src={LAYERS.") == 2
      and "<Layer src={layers[i]} />" in VISUAL_BOT and VIEW.count("<Arm {...ARMS.") == 2
      and not glob.glob(ROOT + "public/bot/omniflow-bot-arm-*.webp")
      and all('"/bot/%s"' % f in VISUAL_BOT for f in LAYER_FILES) and "const SIZE = { width: 560, height: 846 };" in VISUAL_BOT
      and "aspect-ratio: 560 / 846;" in rule(".figure"), layers)
total = sum(l[1] for l in layers if l)
palms = {side: webp_size(f) if os.path.exists(f) else None for side, f in ((s, ROOT + "public/bot/omniflow-bot-palm-%s.webp" % s) for s in "lr")}
check("open palms: own boxes on the wrist", palms["l"] and palms["r"] and palms["l"][0] == (157, 176) and palms["r"][0] == (157, 175)
      and 'size: { width: 157, height: 176 }, box: [-10.16, 61.64, 27.95, 20.86]' in VISUAL_BOT
      and 'size: { width: 157, height: 175 }, box: [82.42, 61.71, 27.95, 20.73]' in VISUAL_BOT
      and "{inner ? <Layer src={layers[i]} /> : <Hand src={layers[i]} palm={palm} />}" in VISUAL_BOT
      and "<Layer src={palm.src} size={palm.size} />" in VISUAL_BOT, palms)
total += sum(p[1] for p in palms.values() if p)
check("layers stay light", all(l and l[1] < 40000 for l in layers) and total < 110000, "%d bytes" % total)
split = read("tools/bot-render/split.py")
check("arm cuts close at the joints", "BAND = 16" in split and "(past_elbow > -8)" in split and "(past_wrist <= 6)" in split
      and "(upper | fore | hand).sum() == arm.sum()" in split, "elbow band socket + wrist overlap")
check("render source ships", all(os.path.exists(ROOT + "tools/bot-render/" + f) for f in ("key.py", "split.py", "motion.py", "omniflow-bot-render.webp",
                                                                                     "omniflow-bot-render-palms.webp"))
      and all(f in read("tools/bot-render/.gitignore") for f in ("robot_rgba.png", "palms_rgba.png"))
      and '("omniflow-bot-render-palms.webp", "palms_rgba.png")' in read("tools/bot-render/key.py")
      and '(palms[..., 3] > 8) & (gy > WRIST_Y - 60)' in split, "re-cut the layers; intermediates ignored")
small = re.search(r"@media \(max-width: 639px\) \{(.*?)\n\}\n", CSS, re.S)
check("phones: taller stage, bigger robot, readable lines", small is not None and "aspect-ratio: 5 / 6;" in small.group(1)
      and "left: 25%;\n    top: 21.5%;\n    width: 50%;" in small.group(1) and "font-size: clamp(12.5px, 3.9cqw, 15px);" in small.group(1)
      and "width: clamp(34px, 12cqw, 52px);" in small.group(1)
      and "@media (min-width: 640px) and (max-width: 1023px) {\n  .figure {\n    left: 27%;\n    top: 20%;\n    width: 46%;" in CSS, "responsive")
check("depth parallax", "transform: translate(calc(var(--lx, 0) * var(--z) * 0.5cqw), calc(var(--ly, 0) * var(--z) * 0.25cqw));" in rule(".depth")
      and VIEW.count("<Depth z={") == 5, "nearer planes travel further")
resample = [w for w in ("preserve-3d", "rotateY", "rotateX", "perspective", "translateZ") if w in CSS]
check("render stays sharp", not resample, resample or "no 3d re-sampling of the image")
check("pivots match the render", "transform-origin: 50.2% 32.4%;" in rule(".head") and "transform-origin: 25.84% 40.61%;" in rule(".armL")
      and "transform-origin: 74.88% 40.59%;" in rule(".armR"), "neck + shoulders")
check("cursor light per layer", "maskImage: mask, WebkitMaskImage: mask" in VISUAL_BOT and "mix-blend-mode: soft-light;" in rule(".light")
      and "opacity: calc(0.3 + var(--lp, 0) * 0.6);" in rule(".light")
      and "transform: translate(calc(var(--lx, 0) * 20%), calc(var(--ly, 0) * 18%));" in rule(".lightSpot"), "moving key light")
check("light reaches the bubbles", "transform: translate(calc(var(--lx, 0) * -22%), calc(var(--ly, 0) * -22%));" in rule(".bubble::after")
      and "opacity: calc(0.2 + var(--lp, 0) * 0.5);" in rule(".bubble::after"), "same light")
check("standing, not floating", "bot-float" not in CSS and "@keyframes bot-breathe" in CSS and "@keyframes bot-pulse" in CSS
      and "top: 88.7%;" in rule(".platform"), "on the platform")
check("light platform", "className={s.disc}" in VIEW and "s.pulse" in VIEW and 'fill: "var(--bot-floor-shadow)"' in VIEW, "surface")
emoji = [c for c in ALL if ord(c) > 0x2000]
check("no emoji code points", not emoji, emoji[:3])

print("== accessibility ==")

check("one labelled image", 'role="img"' in VIEW and "aria-label={[label, ...spoken].map(sentence).join(" + '" ")}' in VIEW, "a11y")
check("decoration hidden", VISUAL_BOT.count('aria-hidden focusable="false"') == 3 and 'alt=""' in VISUAL_BOT, "decorative")
check("reduced motion = final pose", "@media (prefers-reduced-motion: reduce) {\n  .root *,\n  .root *::after {\n    animation: none !important;" in CSS
      and re.search(r"\.line1 \{[^}]*opacity: 0;", CSS) and re.search(r"\.line2 \{[^}]*opacity: 0;", CSS)
      and re.search(r"\.line3 \{[^}]*opacity: 0;", CSS) and re.search(r"\.line4 \{[^}]*opacity: 0;", CSS)
      and not re.search(r"\.line5 \{[^}]*opacity: 0;", CSS), "calm pose")
check("still mode", ".root[data-static] *," in CSS and 'data-static={animated ? undefined : ""}' in VIEW, "animated=false")
check("nodes not interactive", re.search(r"\.node \{[^}]*pointer-events: none;", CSS) is not None, "decorative")
check("tap wave after intro only", "performance.now() - born < INTRO_MS" in MOTION and ".waving .tap {" in CSS, "no restart")

print("== functional (real tsx) ==")

ts_mod = None
for base in (ROOT, REPO):
    candidate = os.path.join(base, "node_modules", "typescript")
    if os.path.isdir(candidate):
        ts_mod = candidate
        break
node = shutil.which("node")
if not (node and ts_mod):
    check("functional harness", True, "skipped: node/typescript not available")
else:
    env = dict(os.environ, NODE_PATH=os.path.dirname(ts_mod))
    out = subprocess.run([node, os.path.join(HERE, "hero_bot_harness.cjs"), ROOT, ts_mod],
                         capture_output=True, text=True, timeout=120, env=env)
    lines = [line for line in out.stdout.splitlines() if line.startswith(("PASS ", "FAIL "))]
    check("harness ran", out.returncode == 0 and len(lines) >= 29, out.stderr[-300:] or "%d cases" % len(lines))
    for line in lines:
        status, _, name = line.partition(" ")
        check("fn " + name[:60], status == "PASS", name)

summary("hero_bot")
