import {
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  BrainCircuit,
  Building2,
  CalendarCheck,
  CircleHelp,
  Clock,
  CodeXml,
  Compass,
  Database,
  Eye,
  FileText,
  GitBranch,
  Globe,
  Hand,
  HandHeart,
  Hash,
  Headphones,
  History,
  House,
  Inbox,
  KeyRound,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  Lock,
  Mail,
  Map as MapIcon,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Package,
  PlugZap,
  RefreshCcw,
  Repeat,
  Route,
  Scale,
  ScanSearch,
  Send,
  Settings,
  Sheet,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Store,
  Target,
  TrendingUp,
  Truck,
  UserCheck,
  UserPlus,
  UserRound,
  Users,
  WandSparkles,
  Webhook,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "../../../lib/marketing/types";

const REGISTRY: Record<IconName, LucideIcon> = {
  message: MessageCircle,
  messages: MessagesSquare,
  sparkles: Sparkles,
  brain: BrainCircuit,
  book: BookOpen,
  target: Target,
  branch: GitBranch,
  zap: Zap,
  send: Send,
  bag: ShoppingBag,
  package: Package,
  truck: Truck,
  calendar: CalendarCheck,
  help: CircleHelp,
  "user-plus": UserPlus,
  refresh: RefreshCcw,
  headphones: Headphones,
  store: Store,
  webhook: Webhook,
  code: CodeXml,
  sheet: Sheet,
  mail: Mail,
  hash: Hash,
  users: Users,
  database: Database,
  plug: PlugZap,
  scan: ScanSearch,
  workflow: Workflow,
  route: Route,
  bell: Bell,
  clock: Clock,
  hand: Hand,
  eye: Eye,
  shield: ShieldCheck,
  chart: BarChart3,
  layers: Layers,
  user: UserRound,
  inbox: Inbox,
  dashboard: LayoutDashboard,
  settings: Settings,
  bot: Bot,
  history: History,
  scale: Scale,
  list: ListChecks,
  repeat: Repeat,
  cart: ShoppingCart,
  globe: Globe,
  file: FileText,
  wand: WandSparkles,
  trending: TrendingUp,
  megaphone: Megaphone,
  building: Building2,
  house: House,
  lifebuoy: LifeBuoy,
  compass: Compass,
  "heart-hand": HandHeart,
  map: MapIcon,
  key: KeyRound,
  lock: Lock,
  "user-check": UserCheck,
};

/**
 * Renders a named icon from the registry. Decorative by default; pass
 * `label` when the icon carries meaning on its own.
 */
export default function Icon({
  name,
  className = "h-5 w-5",
  label,
}: {
  name: IconName;
  className?: string;
  label?: string;
}) {
  const Component = REGISTRY[name];
  return label ? (
    <Component className={className} role="img" aria-label={label} />
  ) : (
    <Component className={className} aria-hidden />
  );
}
